# Generated by Django 5.2.4 on 2025-08-19 14:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=512)),
                ('authors', models.JSONField(blank=True, null=True)),
                ('thumbnail_url', models.URLField(blank=True, max_length=500)),
                ('language', models.CharField(blank=True, max_length=16)),
                ('published_date_raw', models.CharField(blank=True, max_length=32)),
                ('etag', models.CharField(blank=True, max_length=128)),
                ('last_modified', models.DateTimeField(blank=True, null=True)),
                ('last_fetched_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'indexes': [models.Index(fields=['title'], name='books_book_title_d3218d_idx')],
            },
        ),
    ]
