# Generated by Django 5.2.4 on 2025-08-19 16:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='etag',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='book',
            name='last_fetched_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='book',
            name='last_modified',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
