# Generated by Django 5.2.4 on 2025-08-19 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_book_etag_book_last_fetched_at_book_last_modified'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                ALTER TABLE books_book
                ADD COLUMN IF NOT EXISTS created_at timestamp with time zone DEFAULT NOW();
                ALTER TABLE books_book
                ALTER COLUMN created_at SET NOT NULL;

                ALTER TABLE books_book
                ADD COLUMN IF NOT EXISTS updated_at timestamp with time zone DEFAULT NOW();
                ALTER TABLE books_book
                ALTER COLUMN updated_at SET NOT NULL;
            """,
            reverse_sql="""
                ALTER TABLE books_book DROP COLUMN IF EXISTS updated_at;
                ALTER TABLE books_book DROP COLUMN IF EXISTS created_at;
            """,
        ),
    ]
