# Generated by Django 5.2.4 on 2025-08-19 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='readingstatus',
            options={'verbose_name': 'Reading status', 'verbose_name_plural': 'Reading statuses'},
        ),
    ]
