# Generated by Django 5.2.4 on 2025-08-20 14:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0002_alter_readingstatus_options'),
        ('books', '0003_add_missing_book_timestamps'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='readingstatus',
            name='activity_re_book_id_67f5aa_idx',
        ),
        migrations.AlterUniqueTogether(
            name='readingstatus',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='readingstatus',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_statuses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='readingstatus',
            index=models.Index(fields=['user', 'book'], name='activity_re_user_id_238c2b_idx'),
        ),
        migrations.AddIndex(
            model_name='readingstatus',
            index=models.Index(fields=['status'], name='activity_re_status_31acad_idx'),
        ),
        migrations.AddConstraint(
            model_name='readingstatus',
            constraint=models.UniqueConstraint(fields=('user', 'book'), name='unique_user_book_status'),
        ),
    ]
