# Generated by Django 5.2.4 on 2025-08-31 15:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0006_review'),
        ('books', '0003_add_missing_book_timestamps'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='rating',
            name='uniq_user_book_rating',
        ),
        migrations.RemoveConstraint(
            model_name='review',
            name='uniq_user_book_review',
        ),
        migrations.AddField(
            model_name='rating',
            name='archived_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='rating',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='review',
            name='archived_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name='rating',
            constraint=models.UniqueConstraint(condition=models.Q(('is_archived', False)), fields=('user', 'book'), name='uniq_user_book_rating'),
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.UniqueConstraint(condition=models.Q(('is_archived', False)), fields=('user', 'book'), name='uniq_user_book_review'),
        ),
    ]
